# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kostas/gitSoftware/LastFM-API

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kostas/gitSoftware/LastFM-API

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostas/gitSoftware/LastFM-API/CMakeFiles /home/kostas/gitSoftware/LastFM-API//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostas/gitSoftware/LastFM-API/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LastFMApi

# Build rule for target.
LastFMApi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LastFMApi
.PHONY : LastFMApi

# fast build rule for target.
LastFMApi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/build
.PHONY : LastFMApi/fast

#=============================================================================
# Target rules for targets named CliKit

# Build rule for target.
CliKit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CliKit
.PHONY : CliKit

# fast build rule for target.
CliKit/fast:
	$(MAKE) $(MAKESILENT) -f src/Cli-Kit/CMakeFiles/CliKit.dir/build.make src/Cli-Kit/CMakeFiles/CliKit.dir/build
.PHONY : CliKit/fast

src/LastFmApi.o: src/LastFmApi.cpp.o
.PHONY : src/LastFmApi.o

# target to build an object file
src/LastFmApi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/LastFmApi.cpp.o
.PHONY : src/LastFmApi.cpp.o

src/LastFmApi.i: src/LastFmApi.cpp.i
.PHONY : src/LastFmApi.i

# target to preprocess a source file
src/LastFmApi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/LastFmApi.cpp.i
.PHONY : src/LastFmApi.cpp.i

src/LastFmApi.s: src/LastFmApi.cpp.s
.PHONY : src/LastFmApi.s

# target to generate assembly for a file
src/LastFmApi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/LastFmApi.cpp.s
.PHONY : src/LastFmApi.cpp.s

src/album.o: src/album.cpp.o
.PHONY : src/album.o

# target to build an object file
src/album.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/album.cpp.o
.PHONY : src/album.cpp.o

src/album.i: src/album.cpp.i
.PHONY : src/album.i

# target to preprocess a source file
src/album.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/album.cpp.i
.PHONY : src/album.cpp.i

src/album.s: src/album.cpp.s
.PHONY : src/album.s

# target to generate assembly for a file
src/album.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/album.cpp.s
.PHONY : src/album.cpp.s

src/artist.o: src/artist.cpp.o
.PHONY : src/artist.o

# target to build an object file
src/artist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/artist.cpp.o
.PHONY : src/artist.cpp.o

src/artist.i: src/artist.cpp.i
.PHONY : src/artist.i

# target to preprocess a source file
src/artist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/artist.cpp.i
.PHONY : src/artist.cpp.i

src/artist.s: src/artist.cpp.s
.PHONY : src/artist.s

# target to generate assembly for a file
src/artist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/artist.cpp.s
.PHONY : src/artist.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/track.o: src/track.cpp.o
.PHONY : src/track.o

# target to build an object file
src/track.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/track.cpp.o
.PHONY : src/track.cpp.o

src/track.i: src/track.cpp.i
.PHONY : src/track.i

# target to preprocess a source file
src/track.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/track.cpp.i
.PHONY : src/track.cpp.i

src/track.s: src/track.cpp.s
.PHONY : src/track.s

# target to generate assembly for a file
src/track.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LastFMApi.dir/build.make CMakeFiles/LastFMApi.dir/src/track.cpp.s
.PHONY : src/track.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CliKit"
	@echo "... LastFMApi"
	@echo "... src/LastFmApi.o"
	@echo "... src/LastFmApi.i"
	@echo "... src/LastFmApi.s"
	@echo "... src/album.o"
	@echo "... src/album.i"
	@echo "... src/album.s"
	@echo "... src/artist.o"
	@echo "... src/artist.i"
	@echo "... src/artist.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/track.o"
	@echo "... src/track.i"
	@echo "... src/track.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

